package GUI;
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Henr'y
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    functionality.Controller c;
    public MainFrame() {
        initComponents();
        c = new functionality.Controller();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        UI = new javax.swing.JTabbedPane();
        Flights = new javax.swing.JScrollPane();
        TourPannel3 = new javax.swing.JPanel();
        SearchBox3 = new javax.swing.JPanel();
        SearchOptions3 = new javax.swing.JPanel();
        LabelDate = new javax.swing.JLabel();
        LocationBox3 = new javax.swing.JComboBox();
        FromDay3 = new javax.swing.JComboBox();
        FromMonth3 = new javax.swing.JComboBox();
        FromYear3 = new javax.swing.JComboBox();
        LabelFrom3 = new javax.swing.JLabel();
        LabelTo3 = new javax.swing.JLabel();
        LocationBox4 = new javax.swing.JComboBox();
        LocationBox6 = new javax.swing.JComboBox();
        LocationBox7 = new javax.swing.JComboBox();
        LabalATicket = new javax.swing.JLabel();
        LabelCTicket = new javax.swing.JLabel();
        ReturnCB = new javax.swing.JCheckBox();
        ReturnPanel = new javax.swing.JPanel();
        LabelDate2 = new javax.swing.JLabel();
        FromDay5 = new javax.swing.JComboBox();
        FromMonth5 = new javax.swing.JComboBox();
        FromYear5 = new javax.swing.JComboBox();
        VariFliCB = new javax.swing.JCheckBox();
        SearchButton3 = new javax.swing.JButton();
        TourResaults3 = new javax.swing.JScrollPane();
        FlightResaultsP1 = new javax.swing.JPanel();
        Auglysing = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TourResaults4 = new javax.swing.JScrollPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Hotels = new javax.swing.JScrollPane();
        TourPannel2 = new javax.swing.JPanel();
        SearchBox2 = new javax.swing.JPanel();
        SearchOptions2 = new javax.swing.JPanel();
        LabelFrom = new javax.swing.JLabel();
        LabelTo = new javax.swing.JLabel();
        NoB = new javax.swing.JLabel();
        LocationBox2 = new javax.swing.JComboBox();
        FromDay2 = new javax.swing.JComboBox();
        FromMonth2 = new javax.swing.JComboBox();
        FromYear2 = new javax.swing.JComboBox();
        ToDay2 = new javax.swing.JComboBox();
        ToMonth2 = new javax.swing.JComboBox();
        ToYear2 = new javax.swing.JComboBox();
        SearchButton2 = new javax.swing.JButton();
        TourResaults2 = new javax.swing.JScrollPane();
        ResaultPanel2 = new javax.swing.JPanel();
        Auglysing2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Tours = new javax.swing.JScrollPane();
        TourPannel = new javax.swing.JPanel();
        SearchBox = new javax.swing.JPanel();
        SearchOptions = new javax.swing.JPanel();
        Sightseeing = new javax.swing.JCheckBox();
        Fishing = new javax.swing.JCheckBox();
        Hiking = new javax.swing.JCheckBox();
        Glacier = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LocationBox = new javax.swing.JComboBox();
        FromDay = new javax.swing.JComboBox();
        FromMonth = new javax.swing.JComboBox();
        FromYear = new javax.swing.JComboBox();
        ToDay = new javax.swing.JComboBox();
        ToMonth = new javax.swing.JComboBox();
        ToYear = new javax.swing.JComboBox();
        SearchButton = new javax.swing.JButton();
        TourResaults = new javax.swing.JScrollPane();
        ResaultPanel = new javax.swing.JPanel();
        Auglysing3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        user = new javax.swing.JScrollPane();
        TourPannel4 = new javax.swing.JPanel();
        SearchBox4 = new javax.swing.JPanel();
        SearchOptions4 = new javax.swing.JPanel();
        LabelDate1 = new javax.swing.JLabel();
        LabelWindow1 = new javax.swing.JLabel();
        FromDay4 = new javax.swing.JComboBox();
        FromMonth4 = new javax.swing.JComboBox();
        FromYear4 = new javax.swing.JComboBox();
        LabelFrom4 = new javax.swing.JLabel();
        LabelTo4 = new javax.swing.JLabel();
        LabalATicket1 = new javax.swing.JLabel();
        LabelCTicket1 = new javax.swing.JLabel();
        SearchButton4 = new javax.swing.JButton();
        LabelTo5 = new javax.swing.JLabel();
        BoxName = new javax.swing.JTextField();
        BoxAdress = new javax.swing.JTextField();
        BoxGSM = new javax.swing.JTextField();
        BoxEmail = new javax.swing.JTextField();
        BoxFax = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Ticket = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        AdBanner = new javax.swing.JLabel();
        Instructions = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));

        MainPanel.setBackground(new java.awt.Color(204, 204, 255));

        UI.setBackground(new java.awt.Color(255, 204, 153));
        UI.setMaximumSize(new java.awt.Dimension(600, 800));
        UI.setMinimumSize(new java.awt.Dimension(400, 600));

        TourPannel3.setBackground(new java.awt.Color(204, 255, 0));

        SearchBox3.setBackground(new java.awt.Color(220, 220, 240));
        SearchBox3.setPreferredSize(new java.awt.Dimension(1212, 191));

        SearchOptions3.setBackground(new java.awt.Color(235, 235, 235));
        SearchOptions3.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Options"));
        SearchOptions3.setToolTipText("Search Options");
        SearchOptions3.setPreferredSize(new java.awt.Dimension(624, 165));

        LabelDate.setText("Date :");

        LocationBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Any", "Reykjavík", "Southern Iceland", "Easthern Iceland", "Westhern Iceland", "Northern Iceland" }));
        LocationBox3.setToolTipText("");

        FromDay3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        FromDay3.setSelectedItem("Day");
        FromDay3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromDay3ActionPerformed(evt);
            }
        });

        FromMonth3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        FromYear3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2016", "2017", "2018" }));

        LabelFrom3.setText("From:");

        LabelTo3.setText("to:");

        LocationBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Any", "Reykjavík", "Southern Iceland", "Easthern Iceland", "Westhern Iceland", "Northern Iceland" }));
        LocationBox4.setToolTipText("");

        LocationBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "adult-tickets", "1", "2", "3", "4", "5", "6", "7", "8" }));
        LocationBox6.setToolTipText("");

        LocationBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "child-tickets", "1", "2", "3", "4", "5", "6", "7", "8" }));
        LocationBox7.setToolTipText("");

        LabalATicket.setText("Tickets:");

        LabelCTicket.setText("Children:");

        ReturnCB.setText("Look for a flight both ways");
        ReturnPanel.setVisible(false);
        ReturnCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnCBActionPerformed(evt);
            }
        });

        TourResaults4.setVisible(false);

        LabelDate2.setText("Return Date:");

        FromDay5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        FromDay5.setSelectedItem("Day");
        FromDay5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromDay5ActionPerformed(evt);
            }
        });

        FromMonth5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        FromYear5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2016", "2017", "2018" }));

        javax.swing.GroupLayout ReturnPanelLayout = new javax.swing.GroupLayout(ReturnPanel);
        ReturnPanel.setLayout(ReturnPanelLayout);
        ReturnPanelLayout.setHorizontalGroup(
            ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReturnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelDate2)
                    .addGroup(ReturnPanelLayout.createSequentialGroup()
                        .addComponent(FromDay5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FromMonth5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FromYear5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        ReturnPanelLayout.setVerticalGroup(
            ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReturnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelDate2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FromDay5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FromYear5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FromMonth5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        VariFliCB.setText("Allow variable flights (+/- 5 days)");
        VariFliCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VariFliCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SearchOptions3Layout = new javax.swing.GroupLayout(SearchOptions3);
        SearchOptions3.setLayout(SearchOptions3Layout);
        SearchOptions3Layout.setHorizontalGroup(
            SearchOptions3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchOptions3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(SearchOptions3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchOptions3Layout.createSequentialGroup()
                        .addGroup(SearchOptions3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelFrom3)
                            .addComponent(LabalATicket))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SearchOptions3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LocationBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LocationBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SearchOptions3Layout.createSequentialGroup()
                        .addComponent(LabelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(FromDay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FromMonth3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FromYear3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(SearchOptions3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchOptions3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(SearchOptions3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelTo3)
                            .addComponent(LabelCTicket))
                        .addGap(53, 53, 53)
                        .addGroup(SearchOptions3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SearchOptions3Layout.createSequentialGroup()
                                .addComponent(LocationBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ReturnCB))
                            .addComponent(LocationBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SearchOptions3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(VariFliCB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReturnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SearchOptions3Layout.setVerticalGroup(
            SearchOptions3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchOptions3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchOptions3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchOptions3Layout.createSequentialGroup()
                        .addGroup(SearchOptions3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelDate)
                            .addComponent(FromDay3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FromMonth3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FromYear3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VariFliCB))
                        .addGap(20, 20, 20)
                        .addGroup(SearchOptions3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelFrom3)
                            .addComponent(LabelTo3)
                            .addComponent(LocationBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LocationBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReturnCB))
                        .addGap(21, 21, 21)
                        .addGroup(SearchOptions3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LocationBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabalATicket)
                            .addComponent(LocationBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelCTicket)))
                    .addGroup(SearchOptions3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(ReturnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        SearchButton3.setText("Search");
        SearchButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SearchBox3Layout = new javax.swing.GroupLayout(SearchBox3);
        SearchBox3.setLayout(SearchBox3Layout);
        SearchBox3Layout.setHorizontalGroup(
            SearchBox3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchBox3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchOptions3, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        SearchBox3Layout.setVerticalGroup(
            SearchBox3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchBox3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchBox3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(SearchButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchOptions3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SearchOptions3.getAccessibleContext().setAccessibleName("Customer Info");
        SearchOptions3.getAccessibleContext().setAccessibleDescription("Please put in your personal information here");

        javax.swing.GroupLayout FlightResaultsP1Layout = new javax.swing.GroupLayout(FlightResaultsP1);
        FlightResaultsP1.setLayout(FlightResaultsP1Layout);
        FlightResaultsP1Layout.setHorizontalGroup(
            FlightResaultsP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1006, Short.MAX_VALUE)
        );
        FlightResaultsP1Layout.setVerticalGroup(
            FlightResaultsP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        TourResaults3.setViewportView(FlightResaultsP1);

        Auglysing.setBackground(new java.awt.Color(0, 255, 204));

        jLabel5.setText("Hotels you might be intrested in as well");

        javax.swing.GroupLayout AuglysingLayout = new javax.swing.GroupLayout(Auglysing);
        Auglysing.setLayout(AuglysingLayout);
        AuglysingLayout.setHorizontalGroup(
            AuglysingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AuglysingLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );
        AuglysingLayout.setVerticalGroup(
            AuglysingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AuglysingLayout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(jLabel5)
                .addContainerGap(472, Short.MAX_VALUE))
        );

        jLabel6.setText("Flights:");

        jLabel9.setText("Return Flights:");

        javax.swing.GroupLayout TourPannel3Layout = new javax.swing.GroupLayout(TourPannel3);
        TourPannel3.setLayout(TourPannel3Layout);
        TourPannel3Layout.setHorizontalGroup(
            TourPannel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TourPannel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TourPannel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SearchBox3, javax.swing.GroupLayout.DEFAULT_SIZE, 1279, Short.MAX_VALUE)
                    .addGroup(TourPannel3Layout.createSequentialGroup()
                        .addGroup(TourPannel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TourResaults3)
                            .addComponent(TourResaults4)
                            .addGroup(TourPannel3Layout.createSequentialGroup()
                                .addGroup(TourPannel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Auglysing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        TourPannel3Layout.setVerticalGroup(
            TourPannel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TourPannel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TourPannel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TourPannel3Layout.createSequentialGroup()
                        .addComponent(TourResaults3, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TourResaults4, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Auglysing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        Flights.setViewportView(TourPannel3);

        UI.addTab("Flights", Flights);

        TourPannel2.setBackground(new java.awt.Color(255, 255, 0));

        SearchBox2.setBackground(new java.awt.Color(220, 220, 240));

        SearchOptions2.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Options"));
        SearchOptions2.setToolTipText("Search Options");
        SearchOptions2.setPreferredSize(new java.awt.Dimension(624, 165));

        LabelFrom.setText("From :");

        LabelTo.setText("To :");

        NoB.setText("Number of Beds:");

        LocationBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "beds", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        LocationBox2.setToolTipText("");

        FromDay2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        FromDay2.setSelectedItem("Day");
        FromDay2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromDay2ActionPerformed(evt);
            }
        });

        FromMonth2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        FromYear2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2016", "2017", "2018" }));

        ToDay2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        ToDay2.setSelectedItem("Day");
        ToDay2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToDay2ActionPerformed(evt);
            }
        });

        ToMonth2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        ToYear2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2016", "2017", "2018" }));

        javax.swing.GroupLayout SearchOptions2Layout = new javax.swing.GroupLayout(SearchOptions2);
        SearchOptions2.setLayout(SearchOptions2Layout);
        SearchOptions2Layout.setHorizontalGroup(
            SearchOptions2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchOptions2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(SearchOptions2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(SearchOptions2Layout.createSequentialGroup()
                        .addComponent(LabelFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FromDay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(NoB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SearchOptions2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchOptions2Layout.createSequentialGroup()
                        .addComponent(FromMonth2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FromYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)
                        .addComponent(LabelTo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ToDay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ToMonth2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ToYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LocationBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SearchOptions2Layout.setVerticalGroup(
            SearchOptions2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchOptions2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchOptions2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelFrom)
                    .addComponent(FromDay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FromMonth2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FromYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTo)
                    .addComponent(ToDay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ToMonth2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ToYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(SearchOptions2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoB)
                    .addComponent(LocationBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        SearchButton2.setText("Search");
        SearchButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SearchBox2Layout = new javax.swing.GroupLayout(SearchBox2);
        SearchBox2.setLayout(SearchBox2Layout);
        SearchBox2Layout.setHorizontalGroup(
            SearchBox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchBox2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchOptions2, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        SearchBox2Layout.setVerticalGroup(
            SearchBox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchBox2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchBox2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(SearchButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchOptions2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ResaultPanel2Layout = new javax.swing.GroupLayout(ResaultPanel2);
        ResaultPanel2.setLayout(ResaultPanel2Layout);
        ResaultPanel2Layout.setHorizontalGroup(
            ResaultPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1002, Short.MAX_VALUE)
        );
        ResaultPanel2Layout.setVerticalGroup(
            ResaultPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );

        TourResaults2.setViewportView(ResaultPanel2);

        Auglysing2.setBackground(new java.awt.Color(0, 255, 204));

        jLabel7.setText("Tours you might be intrested in as well");

        javax.swing.GroupLayout Auglysing2Layout = new javax.swing.GroupLayout(Auglysing2);
        Auglysing2.setLayout(Auglysing2Layout);
        Auglysing2Layout.setHorizontalGroup(
            Auglysing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Auglysing2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        Auglysing2Layout.setVerticalGroup(
            Auglysing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Auglysing2Layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(jLabel7)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jLabel10.setText("Search resaults:");

        javax.swing.GroupLayout TourPannel2Layout = new javax.swing.GroupLayout(TourPannel2);
        TourPannel2.setLayout(TourPannel2Layout);
        TourPannel2Layout.setHorizontalGroup(
            TourPannel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TourPannel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TourPannel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TourPannel2Layout.createSequentialGroup()
                        .addComponent(TourResaults2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Auglysing2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TourPannel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        TourPannel2Layout.setVerticalGroup(
            TourPannel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TourPannel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TourPannel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TourResaults2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Auglysing2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 349, Short.MAX_VALUE))
        );

        Hotels.setViewportView(TourPannel2);

        UI.addTab("Hotels", Hotels);

        TourPannel.setBackground(new java.awt.Color(255, 204, 0));

        SearchBox.setBackground(new java.awt.Color(204, 204, 255));

        SearchOptions.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Options"));
        SearchOptions.setToolTipText("Search Options");
        SearchOptions.setPreferredSize(new java.awt.Dimension(520, 165));

        Sightseeing.setText("Sightseeing");

        Fishing.setText("Fishing");

        Hiking.setText("Hiking");

        Glacier.setText("Glacier Trips");

        jLabel1.setText("From :");

        jLabel2.setText("To :");

        jLabel3.setText("Location :");

        LocationBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Any", "Reykjavík", "Southern Iceland", "Easthern Iceland", "Westhern Iceland", "Northern Iceland" }));
        LocationBox.setToolTipText("");

        FromDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        FromDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromDayActionPerformed(evt);
            }
        });

        FromMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        FromYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2016", "2017", "2018" }));
        FromYear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ToDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        ToDay.setSelectedItem("Day");
        ToDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToDayActionPerformed(evt);
            }
        });

        ToMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        ToYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2016", "2017", "2018" }));

        javax.swing.GroupLayout SearchOptionsLayout = new javax.swing.GroupLayout(SearchOptions);
        SearchOptions.setLayout(SearchOptionsLayout);
        SearchOptionsLayout.setHorizontalGroup(
            SearchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchOptionsLayout.createSequentialGroup()
                .addGroup(SearchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchOptionsLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(SearchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SearchOptionsLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LocationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SearchOptionsLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FromDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FromMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FromYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ToDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ToMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ToYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SearchOptionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Sightseeing)
                        .addGap(18, 18, 18)
                        .addComponent(Fishing)
                        .addGap(18, 18, 18)
                        .addComponent(Hiking)
                        .addGap(18, 18, 18)
                        .addComponent(Glacier)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SearchOptionsLayout.setVerticalGroup(
            SearchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sightseeing)
                    .addComponent(Fishing)
                    .addComponent(Hiking)
                    .addComponent(Glacier))
                .addGap(18, 18, 18)
                .addGroup(SearchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(SearchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FromDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FromMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FromYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SearchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ToDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ToMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ToYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SearchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(LocationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SearchBoxLayout = new javax.swing.GroupLayout(SearchBox);
        SearchBox.setLayout(SearchBoxLayout);
        SearchBoxLayout.setHorizontalGroup(
            SearchBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchOptions, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        SearchBoxLayout.setVerticalGroup(
            SearchBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(SearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ResaultPanelLayout = new javax.swing.GroupLayout(ResaultPanel);
        ResaultPanel.setLayout(ResaultPanelLayout);
        ResaultPanelLayout.setHorizontalGroup(
            ResaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        ResaultPanelLayout.setVerticalGroup(
            ResaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 856, Short.MAX_VALUE)
        );

        TourResaults.setViewportView(ResaultPanel);

        Auglysing3.setBackground(new java.awt.Color(0, 255, 204));

        jLabel8.setText("Hotels you might be intrested in as well");

        javax.swing.GroupLayout Auglysing3Layout = new javax.swing.GroupLayout(Auglysing3);
        Auglysing3.setLayout(Auglysing3Layout);
        Auglysing3Layout.setHorizontalGroup(
            Auglysing3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Auglysing3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        Auglysing3Layout.setVerticalGroup(
            Auglysing3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Auglysing3Layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(jLabel8)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TourPannelLayout = new javax.swing.GroupLayout(TourPannel);
        TourPannel.setLayout(TourPannelLayout);
        TourPannelLayout.setHorizontalGroup(
            TourPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TourPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TourPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TourPannelLayout.createSequentialGroup()
                        .addComponent(TourResaults)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Auglysing3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        TourPannelLayout.setVerticalGroup(
            TourPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TourPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TourPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TourResaults, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Auglysing3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 352, Short.MAX_VALUE))
        );

        Tours.setViewportView(TourPannel);

        UI.addTab("Tours", Tours);

        TourPannel4.setBackground(new java.awt.Color(255, 153, 0));

        SearchBox4.setBackground(new java.awt.Color(220, 220, 240));

        SearchOptions4.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer information"));
        SearchOptions4.setToolTipText("Customer Credentials");

        LabelDate1.setText("Name*:");

        LabelWindow1.setText("Phone number:");

        FromDay4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        FromDay4.setSelectedItem("Day");
        FromDay4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromDay4ActionPerformed(evt);
            }
        });

        FromMonth4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        FromYear4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2016", "2017", "2018" }));

        LabelFrom4.setText("Date of Birth:");

        LabelTo4.setText("fax*:");

        LabalATicket1.setText("Address");

        LabelCTicket1.setText("*required");

        SearchButton4.setText("Submit");
        SearchButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButton4ActionPerformed(evt);
            }
        });

        LabelTo5.setText("e-mail:");

        BoxName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxNameActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 255, 204));

        jLabel4.setText("Auglýing fyrir E-Ð");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jLabel4)
                .addContainerGap(226, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(104, 104, 104))
        );

        javax.swing.GroupLayout SearchOptions4Layout = new javax.swing.GroupLayout(SearchOptions4);
        SearchOptions4.setLayout(SearchOptions4Layout);
        SearchOptions4Layout.setHorizontalGroup(
            SearchOptions4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchOptions4Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(SearchOptions4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchOptions4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(SearchOptions4Layout.createSequentialGroup()
                            .addComponent(LabelTo4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BoxFax, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SearchOptions4Layout.createSequentialGroup()
                            .addComponent(LabelFrom4)
                            .addGap(23, 23, 23)
                            .addGroup(SearchOptions4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(SearchOptions4Layout.createSequentialGroup()
                                    .addComponent(FromDay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(FromMonth4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(FromYear4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(BoxName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BoxAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(SearchOptions4Layout.createSequentialGroup()
                        .addGroup(SearchOptions4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SearchOptions4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(SearchOptions4Layout.createSequentialGroup()
                                    .addComponent(LabelTo5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BoxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(LabelDate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabalATicket1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(SearchOptions4Layout.createSequentialGroup()
                                    .addComponent(LabelWindow1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(BoxGSM, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(LabelCTicket1))
                        .addGap(49, 49, 49)
                        .addComponent(SearchButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        SearchOptions4Layout.setVerticalGroup(
            SearchOptions4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchOptions4Layout.createSequentialGroup()
                .addGroup(SearchOptions4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchOptions4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(SearchOptions4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelDate1)
                            .addComponent(BoxName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SearchOptions4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabalATicket1)
                            .addComponent(BoxAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(SearchOptions4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelWindow1)
                            .addComponent(BoxGSM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SearchOptions4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelTo5)
                            .addComponent(BoxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SearchOptions4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelTo4)
                            .addComponent(BoxFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SearchOptions4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelFrom4)
                            .addComponent(FromDay4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FromMonth4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FromYear4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LabelCTicket1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout SearchBox4Layout = new javax.swing.GroupLayout(SearchBox4);
        SearchBox4.setLayout(SearchBox4Layout);
        SearchBox4Layout.setHorizontalGroup(
            SearchBox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchBox4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchOptions4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        SearchBox4Layout.setVerticalGroup(
            SearchBox4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchBox4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchOptions4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout TourPannel4Layout = new javax.swing.GroupLayout(TourPannel4);
        TourPannel4.setLayout(TourPannel4Layout);
        TourPannel4Layout.setHorizontalGroup(
            TourPannel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TourPannel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TourPannel4Layout.setVerticalGroup(
            TourPannel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TourPannel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        user.setViewportView(TourPannel4);

        UI.addTab("Customer info", user);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1303, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1062, Short.MAX_VALUE)
        );

        Ticket.setViewportView(jPanel1);

        UI.addTab("Ticket", Ticket);

        Welcome.setText("Welcome to AdvisorNator.com");

        AdBanner.setText("Here you will find your dream-trip or something like that");

        Instructions.setText("Please fill out the forms down below and you are on your way towards your fantasy");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AdBanner)
                            .addComponent(Instructions)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(419, 419, 419)
                                .addComponent(Welcome)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Welcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AdBanner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Instructions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UI, javax.swing.GroupLayout.PREFERRED_SIZE, 1078, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1181, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FromDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FromDayActionPerformed

    private void ToDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToDayActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void FromDay2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromDay2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FromDay2ActionPerformed

    private void ToDay2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToDay2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToDay2ActionPerformed

    private void SearchButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchButton2ActionPerformed

    private void FromDay3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromDay3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FromDay3ActionPerformed

    private void SearchButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButton3ActionPerformed
        // TODO add your handling code here:
        int temp = 2015 + FromYear3.getSelectedIndex();
        Date D = new Date(temp, FromMonth3.getSelectedIndex(), FromDay3.getSelectedIndex());
        
        System.out.println((String)LocationBox3.getSelectedItem() + " " + (String)LocationBox4.getSelectedItem()+ " " +
                                                                    LocationBox6.getSelectedIndex() + " " + LocationBox6.getSelectedIndex()+ " " + D+ " " + null+ " " + VariFliCB.isSelected());
        
        functionality.flight.Flight[] flights = c.searchFlights((String)LocationBox3.getSelectedItem(), (String)LocationBox4.getSelectedItem(),
                                                                    LocationBox6.getSelectedIndex() , LocationBox6.getSelectedIndex(), D, null, VariFliCB.isSelected());
        GUI.FlightList.displayFlights(flights, FlightResaultsP1);
    }//GEN-LAST:event_SearchButton3ActionPerformed

    private void FromDay4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromDay4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FromDay4ActionPerformed

    private void SearchButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchButton4ActionPerformed

    private void BoxNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxNameActionPerformed

    private void FromDay5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromDay5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FromDay5ActionPerformed

    private void ReturnCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnCBActionPerformed
        // TODO add your handling code here:
        if(ReturnCB.isSelected()){
            ReturnPanel.setVisible(true);
            TourResaults4.setVisible(true);
        } else {
            ReturnPanel.setVisible(false);
            TourResaults4.setVisible(false);
        }
    }//GEN-LAST:event_ReturnCBActionPerformed

    private void VariFliCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VariFliCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VariFliCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdBanner;
    private javax.swing.JPanel Auglysing;
    private javax.swing.JPanel Auglysing2;
    private javax.swing.JPanel Auglysing3;
    private javax.swing.JTextField BoxAdress;
    private javax.swing.JTextField BoxEmail;
    private javax.swing.JTextField BoxFax;
    private javax.swing.JTextField BoxGSM;
    private javax.swing.JTextField BoxName;
    private javax.swing.JCheckBox Fishing;
    private javax.swing.JPanel FlightResaultsP1;
    private javax.swing.JScrollPane Flights;
    private javax.swing.JComboBox FromDay;
    private javax.swing.JComboBox FromDay2;
    private javax.swing.JComboBox FromDay3;
    private javax.swing.JComboBox FromDay4;
    private javax.swing.JComboBox FromDay5;
    private javax.swing.JComboBox FromMonth;
    private javax.swing.JComboBox FromMonth2;
    private javax.swing.JComboBox FromMonth3;
    private javax.swing.JComboBox FromMonth4;
    private javax.swing.JComboBox FromMonth5;
    private javax.swing.JComboBox FromYear;
    private javax.swing.JComboBox FromYear2;
    private javax.swing.JComboBox FromYear3;
    private javax.swing.JComboBox FromYear4;
    private javax.swing.JComboBox FromYear5;
    private javax.swing.JCheckBox Glacier;
    private javax.swing.JCheckBox Hiking;
    private javax.swing.JScrollPane Hotels;
    private javax.swing.JLabel Instructions;
    private javax.swing.JLabel LabalATicket;
    private javax.swing.JLabel LabalATicket1;
    private javax.swing.JLabel LabelCTicket;
    private javax.swing.JLabel LabelCTicket1;
    private javax.swing.JLabel LabelDate;
    private javax.swing.JLabel LabelDate1;
    private javax.swing.JLabel LabelDate2;
    private javax.swing.JLabel LabelFrom;
    private javax.swing.JLabel LabelFrom3;
    private javax.swing.JLabel LabelFrom4;
    private javax.swing.JLabel LabelTo;
    private javax.swing.JLabel LabelTo3;
    private javax.swing.JLabel LabelTo4;
    private javax.swing.JLabel LabelTo5;
    private javax.swing.JLabel LabelWindow1;
    private javax.swing.JComboBox LocationBox;
    private javax.swing.JComboBox LocationBox2;
    private javax.swing.JComboBox LocationBox3;
    private javax.swing.JComboBox LocationBox4;
    private javax.swing.JComboBox LocationBox6;
    private javax.swing.JComboBox LocationBox7;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel NoB;
    private javax.swing.JPanel ResaultPanel;
    private javax.swing.JPanel ResaultPanel2;
    private javax.swing.JCheckBox ReturnCB;
    private javax.swing.JPanel ReturnPanel;
    private javax.swing.JPanel SearchBox;
    private javax.swing.JPanel SearchBox2;
    private javax.swing.JPanel SearchBox3;
    private javax.swing.JPanel SearchBox4;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton SearchButton2;
    private javax.swing.JButton SearchButton3;
    private javax.swing.JButton SearchButton4;
    private javax.swing.JPanel SearchOptions;
    private javax.swing.JPanel SearchOptions2;
    private javax.swing.JPanel SearchOptions3;
    private javax.swing.JPanel SearchOptions4;
    private javax.swing.JCheckBox Sightseeing;
    private javax.swing.JScrollPane Ticket;
    private javax.swing.JComboBox ToDay;
    private javax.swing.JComboBox ToDay2;
    private javax.swing.JComboBox ToMonth;
    private javax.swing.JComboBox ToMonth2;
    private javax.swing.JComboBox ToYear;
    private javax.swing.JComboBox ToYear2;
    private javax.swing.JPanel TourPannel;
    private javax.swing.JPanel TourPannel2;
    private javax.swing.JPanel TourPannel3;
    private javax.swing.JPanel TourPannel4;
    private javax.swing.JScrollPane TourResaults;
    private javax.swing.JScrollPane TourResaults2;
    private javax.swing.JScrollPane TourResaults3;
    private javax.swing.JScrollPane TourResaults4;
    private javax.swing.JScrollPane Tours;
    private javax.swing.JTabbedPane UI;
    private javax.swing.JCheckBox VariFliCB;
    private javax.swing.JLabel Welcome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane user;
    // End of variables declaration//GEN-END:variables
}
