/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package other;

import javax.swing.JComponent;
import java.util.*;

/**
 *
 * @author skulii
 */
public class ScrollPaneTest extends javax.swing.JFrame {

    /**
     * Creates new form ScrollPaneTest
     */
    public ScrollPaneTest() {
        initComponents();
        
        
        functionality.daytours.Trip[] trips = new functionality.daytours.Trip[5];
        
        trips[0] = new functionality.daytours.Trip(0, "Sightseeing", "20/04/2016", "8:00", "7:30", "Golden Circle", 10, 8, 24999);
        trips[1] = new functionality.daytours.Trip(1, "Glacier", "19/04/2016", "8:00", "7:30", "Langjökull", 10, 8, 54999);
        trips[2] = new functionality.daytours.Trip(2, "Snowmobiling", "21/04/2016", "8:00", "8:30", "Vatnajökull", 10, 8, 104999);
        trips[3] = new functionality.daytours.Trip(3, "Northern Lights", "19/04/2016", "20:00", "4:00", "Suðurnes", 10, 8, 24999);
        trips[4] = new functionality.daytours.Trip(4, "Sightseeing", "22/04/2016", "9:00", "7:30", "Suðurland", 10, 8, 24999);
        
        functionality.flight.Flight flightOut = new functionality.flight.Flight("Icelandair", 5, 200, "LHR", "KEF", 25999, 20, new Date());
        functionality.flight.Flight flightHome = new functionality.flight.Flight("Icelandair", 5, 200, "KEF", "LHR", 25999, 20, new Date());
        functionality.hotel.Hotel hotel = new functionality.hotel.Hotel("Hótel Adam", "Reykjavík", "Double Room", 24999);
        
        other.UserInfo userinfo = new other.UserInfo("Skúli Ingvarsson", "Granaskjól 90", "7705747", "00000", "bla@bla.is", new Date());
        GUI.Ticket.createTicket(container, userinfo, flightOut, flightHome, hotel, trips[0]);
        //GUI.HotelList.displayHotels(hotels, container);
        //GUI.FlightList.displayFlights(flights, container);
        //GUI.TripList.displayTrips(trips, container);
        // Display them
        //displayResults(results, container);
    }
    
        // Add the results to the container
    private void displayResults(javax.swing.JComponent[] results, javax.swing.JComponent container) {
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(container);
        container.setLayout(layout);
            
        javax.swing.GroupLayout.ParallelGroup horizontalGroup = layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER);
        for (JComponent result : results) {
            horizontalGroup.addComponent(result);
        }
        layout.setHorizontalGroup(horizontalGroup);
        javax.swing.GroupLayout.SequentialGroup verticalGroup = layout.createSequentialGroup();
        verticalGroup.addContainerGap();
        for (JComponent result : results) {
            verticalGroup.addComponent(result);
            verticalGroup.addGap(0, 10, Short.MAX_VALUE);
        }
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addGroup(verticalGroup));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(container);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScrollPaneTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScrollPaneTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScrollPaneTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScrollPaneTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScrollPaneTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
